# Make sure that before you
# run the docker-compose that you have run
# $ yarn docker-build
version: '3'

services:
  backstage:
    image: 'example-backend:latest'
    ports:
      - '7000:7000'
    environment:
      NODE_ENV: development
